POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Erkki",
    "number": "034-234546"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Keke",
    "number": "034-234546"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "g",
    "number": "09-86149854"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Kalle"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{

}

###
PUT http://localhost:3001/api/persons/3
Content-Type: application/json

{
    "name": "g",
    "number": "09-86149854"
}


###
POST https://twilight-breeze-8208.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Kalle",
    "number": "09-86149854"
}